### ISSUE TITLE
File does not close

### ISSUE THREAD

**Issue by Pierre-Louis-Boutruche** [intake/intake-xarray#148]
When using Intake.open_netcdf('example.nc') and closing via ds.close(), the file is not closed, which causes problems when you want to delete the file in the program, for example.

In Intake-xarray/base.py
```python
def close(self):
    """Delete open file from memory"""
    if self._ds is not None:
        self._ds.close() #Closes the file correctly
    self._ds = None
    self._schema = None
```
Without this modification, here's the error I get when I try to delete the netcdf file:
`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'data_2024-07-31.nc'`

**Comment by martindurant** [comment]
I wonder if you would care testing with the very much rewritten code in https://github.com/intake/intake-xarray/pull/147 ?

**Comment by Pierre-Louis-Boutruche** [comment]
How can I test with this branch?

**Comment by martindurant** [comment]
```
pip install git+https://github.com/martindurant/intake-xarray.git@intake2
```

**Comment by martindurant** [comment]
What version of python is this? You may nee `hatch` installed first.

**Comment by Pierre-Louis-Boutruche** [comment]
I downloaded python 3.10, and was able to install intake2 correctly.
Traceback (most recent call last):
  File "C:\Users\pierre.louis.boutruc\Documents\git\test\test_udal\beacon.py", line 145, in <module>
    results = broker._execute_argo(params)
  File "C:\Users\pierre.louis.boutruc\Documents\git\test\test_udal\beacon.py", line 130, in _execute_argo
    ds.close()
AttributeError: 'NetCDFSource' object has no attribute 'close'

When I don't use ds.close() but directly os.remove, I can't because the file is being used by another process.

**Comment by martindurant** [comment]
That's right, `close()` is gone all together, and the file should only be open *during* the call to read(). I could readd `close()` as a no-op.

**Comment by martindurant** [comment]
I wonder if xarray itself keeps hold of an open file? Do you know if you get the same behaviour is you do a
```
ds = xr.open_dataset(...)
```

**Comment by Pierre-Louis-Boutruche** [comment]
With this code:
```python
import xarray as xr
import os

ds = xr.open_dataset("data/iddas_argo_[2015-07-05]_[2020-01-01].nc")

df = ds.to_dataframe()

ds.close()
os.remove("data/iddas_argo_[2015-07-05]_[2020-01-01].nc")
```
Output:
```bash
$ python test.py 
Traceback (most recent call last):
  File "C:\Users\pierre.louis.boutruc\Documents\git\test\test_udal\test.py", line 8, in <module>
    os.remove("data/iddas_argo_[2015-07-05]_[2020-01-01].nc")
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'data/iddas_argo_[2015-07-05]_[2020-01-01].nc'
```

But if I add ds.close(), this code works

**Comment by martindurant** [comment]
With the intake2 version of this repo, you should be able to do

```
ds = cat.source.read()
```
and thereafter only need ds.close() as you would with xarray alone.
